### ISSUE TITLE
Updated "permissions" gif for Mac users for WPE

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#431] opened 2024-05-21 12:27 UTC
Currently it shows accessing the permissions through the EAP

https://docs.pieces.app/product-highlights-and-benefits/live-context

**Comment by mack-at-pieces** [comment] 2024-05-21 14:52
This is a duplicate of #428 . Closing.

**Closed by mack-at-pieces** 2024-05-21 14:52 UTC
